### ISSUE TITLE
Duplicate defintion  in generated rust code for ra4m1 SVD

### ISSUE THREAD

**Issue by claudex** [rust-embedded/svd2rust#860] opened 2024-08-28 20:07 UTC
Hello,

When running svd2rust with the latest commit on [Renesas ra4m1 svd](https://github.com/user-attachments/files/16788347/R7FA4M1AB.svd.gz), there is a lot of duplicated definitions [error.log](https://github.com/user-attachments/files/16788338/error.log)

Here is the generated code: 
[lib.rs.txt](https://github.com/user-attachments/files/16788376/lib.rs.txt)

I'm a newbie in embedded development, I hope that's enough information.

**Comment by burrbull** [comment] 2024-10-19 09:03
duplicate of #852

**Closed by burrbull** 2024-10-19 09:03 UTC

**Comment by claudex** [comment] 2024-10-19 12:44
Sorry, I didn't see it when I created the issue. Thanks for the followup.
